import test from 'node:test';import assert from 'node:assert/strict';
import {SkavioClient} from '../javascript/index.mjs';
import operations from '../javascript/operations.mjs';
import {readFileSync} from 'node:fs';
test('new bulk controls preserve idempotency and do not retry',async()=>{for(const action of ['pauseBulk','cancelBulk']){let calls=0,headers;const c=new SkavioClient('key',{fetchImpl:async(u,o)=>{calls++;headers=o.headers;return new Response('{}',{status:503});}});await assert.rejects(c[action]('bulk','persisted-control-190'));assert.equal(calls,1);assert.equal(headers['Idempotency-Key'],'persisted-control-190');}});
test('notification admin session excludes bearer',async()=>{let headers;const c=new SkavioClient('key',{fetchImpl:async(u,o)=>{headers=o.headers;return new Response('{}');}});await c.updateNotificationSettings({enabled:false},'synthetic-admin-session-190');assert.equal(headers.Authorization,undefined);assert.equal(headers.Cookie,'skavio_web_account=synthetic-admin-session-190');});
test('notification cookie injection rejected',async()=>{const c=new SkavioClient('key',{fetchImpl:()=>assert.fail('must not send')});await assert.rejects(c.updateNotificationSettings({},'x\r\nInjected: header'));});
test('OpenAPI registry and TypeScript parity',()=>{const spec=JSON.parse(readFileSync(new URL('../../openapi-v1.json',import.meta.url)));const expected=Object.values(spec.paths).flatMap(i=>Object.entries(i).filter(([m])=>['get','post','put','patch','delete'].includes(m)).map(([,o])=>o.operationId));assert.deepEqual(Object.keys(operations).sort(),expected.sort());const types=readFileSync(new URL('../javascript/index.d.ts',import.meta.url),'utf8');for(const name of Object.getOwnPropertyNames(SkavioClient.prototype).filter(n=>n!=='constructor'))assert.ok(types.includes(name+'(')||types.includes(name+'<'),name);});

test('bulk retry convenience matches OpenAPI route and key',async()=>{let received;const c=new SkavioClient('key',{fetchImpl:async(u,o)=>{received={url:String(u),...o};return new Response('{}');}});await c.retryBulk('synthetic-bulk','durable-retry-190');assert.equal(received.url,'https://www.skavio.eu/v1/bulks/synthetic-bulk/retry-failed');assert.equal(received.headers['Idempotency-Key'],'durable-retry-190');assert.ok(Object.values(operations).some(o=>o.path==='/v1/bulks/{bulk_id}/retry-failed'&&o.idempotency_required));});
